### ISSUE TITLE
RSS for blog posts

### ISSUE THREAD

**Issue by bhean** [jacobtomlinson/website#159]
Hey! I really like your blog posts, thanks for sharing!
I use to read a lot of posts about these kind of topics, but I can't visit all these websites every day/week/month to check if there are new content, so IMHO you should add an RSS/Atom/whatever to allow readers to fetch your posts in an easier way. It's just a suggestion! Thanks!

**Comment by jacobtomlinson** [comment]
Glad you like the posts! This blog already has a feed, your feed reader should've picked it up but here's the link in case it didn't.

https://jacobtomlinson.dev/feed.xml

**Comment by bhean** [comment]
OMG, I was trying to find it before I opened the issue, but my reader (Reeder 5) didn't find it! 😲 
Thanks for the fast reply! Best regards!
