### ISSUE TITLE
Possibly incorrect/outdated Vault policy?

### ISSUE THREAD

**Issue by athajaerel** [jacobtomlinson/website#163]
https://jacobtomlinson.dev/posts/2017/how-to-create-a-seal-only-token-for-hashicorp-vault/

Shouldn't the policy be:

```
path "sys/seal" {
  capabilities = ["update", "sudo"]
}
```

instead of

```
path "/sys/seal" {
  policy = "sudo"
}
```

as it is now? Although Vault does accept your version. Perhaps it's an old format which is no longer promoted.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Yeah this post is 5 years old and I haven't used Vault for a couple of years so things may be a little out of date.

I've pushed a couple of changes. Many thanks!
